api:
  config-server:
    url: http://localhost:8888
  gateway-service:
    url: http://localhost:8080
  auth-service:
    url: http://localhost:8081
  user-service:
    url: http://localhost:8082

spring:
  spring:
    kafka:
      bootstrap-servers: localhost:29092
  data:
    redis:
      host: localhost
      port: 6379

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411

loki:
  uri: http://localhost:3100/loki/api/v1/push