api:
  config-server:
    url: http://config-server:8888
  gateway-service:
    url: http://gateway-service:8080
  auth-service:
    url: http://auth-service:8081
  user-service:
    url: http://user-service:8082

spring:
  kafka:
    bootstrap-servers: kafka:29092
  data:
    redis:
      host: redis
      port: 6379

management:
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://tempo:9411}

loki:
  uri: ${LOKI_URI:http://loki:3100/loki/api/v1/push}