api:
  config-server:
    url: http://config-server:8888
  gateway-service:
    url: http://gateway-service:8080
  auth-service:
    url: http://auth-service:8081
  user-service:
    url: http://user-service:8082